env:
  commonjs: true
  es2022: true
  node: true
extends: eslint:recommended
overrides: []
ignorePatterns:
  - Templates/*
parserOptions:
  ecmaVersion: latest
rules:
  no-fallthrough:
    - warn
  no-empty:
    - error
    - allowEmptyCatch: true
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - off
  quotes:
    - warn
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  space-in-parens:
    - warn
    - never
  comma-spacing:
    - error
    - before: false
      after: true
  array-bracket-spacing:
    - error
    - never
    - singleValue: false
      objectsInArrays: false
      arraysInArrays: false
  object-curly-spacing:
    - error
    - always
globals:
  getDirectories: writeable
  sleep: writeable
  log: writeable
