files:
  - source: /Locales/en/
    ignore:
      - /Locales/en/*/
    translation: /Locales/%two_letters_code%/%original_file_name%
  - source: /Locales/en/commands
    translation: /Locales/%two_letters_code%/commands/%original_file_name%
  - source: /Locales/en/events
    translation: /Locales/%two_letters_code%/events/%original_file_name%
