const utils = {
  afk: require('./afk.js'),
  autocompleteGenerator: require('./autocompleteGenerator.js'),
  BackupSystem: require('./backupSystem.js'),
  checkForErrors: require('./checkForErrors.js'),
  checkTargetManageable: require('./checkTargetManageable.js'),
  commandExecutionWrapper: require('./commandExecutionWrapper.js'),
  commandMention: require('./commandMention.js'),
  componentHandler: require('./componentHandler.js'),
  configValidator: require('./configValidator.js'),
  constants: require('./constants.js'),
  cooldowns: require('./cooldowns.js'),
  DiscordAPIErrorCodes: require('./DiscordAPIErrorCodes.json'),
  errorHandler: require('./errorHandler.js'),
  filename: require('./filename.js'),
  findAllEntries: require('./findAllEntries.js'),
  getAge: require('./getAge.js'),
  getCommands: require('./getCommands.js'),
  getDirectories: require('./getDirectories.js'),
  getTargetChannel: require('./getTargetChannel.js'),
  getTargetMember: require('./getTargetMember.js'),
  getTargetRole: require('./getTargetRole.js'),
  gitpull: require('./gitpull.js'),
  GiveawaysManager: require('./giveawaysManager.js'),
  logSayCommandUse: require('./logSayCommandUse.js'),
  permissionTranslator: require('./permissionTranslator.js'),
  shellExec: require('./shellExec.js'),
  prototypeRegisterer: require('./prototypeRegisterer'),
  timeFormatter: require('./timeFormatter.js'),
  timeValidator: require('./timeValidator.js')
};

module.exports = utils;